name: Python application CPU

on:
  push:
    paths:
      - 'Local-Windows/main.py'
  pull_request:
    paths:
      - 'Local-Windows/main.py'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Local-Windows/requirements.txt
        pip install pyinstaller

    - name: Modify main.py for CPU usage
      run: |
        (Get-Content Local-Windows/main.py) -replace 'model = WhisperModel\("large-v2", device="cuda",  compute_type="int8"\)', 'model = WhisperModel("large-v2", device="cpu",  compute_type="int8")' | Set-Content Local-Windows/main.py

    - name: Build exe with PyInstaller
      run: |
        cd Local-Windows
        pyinstaller --onefile main.py

    - name: Upload EXE as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-application-exe
        path: Local-Windows/dist/main.exe
