name: Python application Cuda

on:
  push:
    paths:
      - 'Local-Windows/main.py'
  pull_request:
    paths:
      - 'Local-Windows/main.py'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Create AutoYT.cmd
      run: |
        echo pip install -r Local-Windows/requirements.txt > Local-Windows/AutoYT.cmd
        echo start "" "main.exe" >> Local-Windows/AutoYT.cmd

    - name: Build exe with PyInstaller
      run: |
        cd Local-Windows
        pyinstaller --onefile main.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Python_application_Cuda
        path: |
          Local-Windows/dist/main.exe
          Local-Windows/AutoYT.cmd
          Local-Windows/requirements.txt
