name: Python application Cuda

on:
  push:
    paths:
      - 'Local-Windows/main.py'
      - 'Local-Windows/AutoYT.cmd'
      - 'Local-Windows/requirements.txt'
  pull_request:
    paths:
      - 'Local-Windows/main.py'
      - 'Local-Windows/AutoYT.cmd'
      - 'Local-Windows/requirements.txt'

jobs:
  package-and-upload:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Local-Windows/requirements.txt

    - name: Package Files
      run: |
        Compress-Archive -Path Local-Windows\AutoYT.cmd, Local-Windows\main.py, Local-Windows\requirements.txt -DestinationPath "Python application Cuda.zip"

    - name: Upload Packaged Files as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Python-application-Cuda
        path: "Python application Cuda.zip"
