name: Python application Cuda

on:
  push:
    paths:
      - 'Local-Windows/main.py'
  pull_request:
    paths:
      - 'Local-Windows/main.py'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build exe with PyInstaller
      run: |
        cd Local-Windows
        pyinstaller --onefile main.py
        Move .\dist\main.exe .\main.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: application-bundle
        path: |
          Local-Windows/main.exe
          Local-Windows/AutoYT.cmd
          Local-Windows/requirements.txt
